### ISSUE TITLE
No enum constant 

### ISSUE THREAD

**Issue by longshang** [Ecwid/consul-api#98] opened 2017-05-02 03:58 UTC
version：1.2.1
log:
Caused by: java.lang.IllegalArgumentException: No enum constant com.ecwid.consul.v1.health.model.Check.CheckStatus.passing
	at java.lang.Enum.valueOf(Enum.java:238)
	at com.google.gson.DefaultTypeAdapters$EnumTypeAdapter.deserialize(DefaultTypeAdapters.java:410)
	at com.google.gson.DefaultTypeAdapters$EnumTypeAdapter.deserialize(DefaultTypeAdapters.java:400)
	at com.google.gson.JsonDeserializerExceptionWrapper.deserialize(JsonDeserializerExceptionWrapper.java:50)

**Comment by jpitz** [comment] 2017-05-09 20:01
This also happens on the Behavior Enum from the SessionConsulClient

**Comment by jpitz** [comment] 2017-05-09 20:23
Looking at the code in depth a little more, it seems like the issue is that they are using this SerializedName annotation that looks like it is intended to be used for the keys of json objects and not the values.

**Comment by jpitz** [comment] 2017-05-09 20:45
Looking at the Gson TypeAdapters class, I can see an EnumTypeAdapter that *should* be handling this appropriately:

https://github.com/google/gson/blob/master/gson/src/main/java/com/google/gson/internal/bind/TypeAdapters.java#L772-L805

Then looking at the GsonBuilder class, it looks like it does not add the enum type factory by default when constructing the Gson object:

https://github.com/google/gson/blob/master/gson/src/main/java/com/google/gson/GsonBuilder.java#L562-L567

```
    List<TypeAdapterFactory> factories = new ArrayList<TypeAdapterFactory>();
    factories.addAll(this.factories);
    Collections.reverse(factories);
    factories.addAll(this.hierarchyFactories);
    addTypeAdaptersForDate(datePattern, dateStyle, timeStyle, factories);
```

Seems like a one line fix to register the enum type adapter for the GsonBuilder

**Comment by jpitz** [comment] 2017-05-09 20:48
Open pull request to resolve this issue: https://github.com/Ecwid/consul-api/pull/99

**Comment by jpitz** [comment] 2017-05-09 21:03
Added a unit test so that it ensures that we can deserialize @SerializedName enumeration values properly

**Comment by jpitz** [comment] 2017-05-09 21:46
Something else odd is happening here and I don't think my PR will fix this exception. I threw together a dummy example just to see if it works by default and it appears to work without throwing an exception:

```
    @Test
    public void testFailure() {
        final Gson gson = new GsonBuilder()
                .create();

        final Session session = gson.fromJson(TEST_JSON_STRING, Session.class);
    }
```

My bet is that it has to do with some of the unwrapping that is occurring with the TypeToken object that seems to be scattered all throughout the code base:

```
new TypeToken<Map<String, String>>() {}.getType()
```

Anyone else have any thoughts?

**Comment by jpitz** [comment] 2017-05-23 22:06
Discovered what the issue was on our end: We wound up with two different gson jars on the classpath which was resulting in a really old version that did not properly handle enum types of this fashion to be parsed properly.

**Comment by longshang** [comment] 2017-05-24 06:51
@jpitz ，thank you! let me try.

**Comment by vgv** [comment] 2017-06-12 12:11
@jpitz Great to hear that problem has solved, I will close this issue

**Closed by vgv** 2017-06-12 12:11 UTC
